#!/bin/bash
# pipe text to this script:
# $ echo "test" | /path/to/script
set -e

mail \
    --subject "${1:-Pipeline alert}" \
    --append "From: alfred@elifesciences.org" \
    {{ pillar.alfred.maintainer }}

