#!/bin/bash
{% if salt['elife.cfg']('cfn.outputs.DomainName') %}
exec java -jar /usr/local/bin/jenkins-cli.jar -s https://{{ salt['elife.cfg']('cfn.outputs.DomainName') }} -noKeyAuth "$@" --username {{ pillar.alfred.jenkins.user }} --password {{ pillar.alfred.jenkins.password }}
{% else %}
exec java -jar /usr/local/bin/jenkins-cli.jar -s http://localhost:80 "$@"
{% endif %}
