#!/bin/bash
set -e
set -o pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 PIPELINE_NAME [MINUTES]"
    echo "Example: $0 test-journal 60"
fi

pipeline="$1"
minutes="${2:-60}"

cd /opt/pipeline-statistics
output=$(mktemp)
if ! python pipeline-last-success-check.py "/var/lib/jenkins/statistics/$pipeline.json" "$minutes" 2>&1 | tee "$output"; then
    /usr/local/bin/pipeline-alert "Pipeline $pipeline has stopped running" < "$output"
fi
