#!/bin/bash
{% if salt['elife.cfg']('cfn.outputs.DomainName') %}
exec java -jar /usr/local/bin/jenkins-cli.jar -s https://{{ salt['elife.cfg']('cfn.outputs.DomainName') }} "$@"
{% else %}
exec java -jar /usr/local/bin/jenkins-cli.jar -s http://localhost:80 "$@"
{% endif %}
